version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_USER=gitplayers
      - POSTGRES_DB=invitation_game
    ports: 
      - 5430:5432
volumes:
  postgresdata: